"""Cross-validation against golden values from the original R package.

``tests/data/r_golden.json`` is generated by ``scripts/r_golden.R`` running
the CRAN package ``strat`` (see the header of that script). R orders strata
and groups by factor levels, Python by sorted unique values, so tables are
matched by label before comparison.
"""

import json
from pathlib import Path

import pytest

from stratindex import srank, strat

RTOL = 1e-9

GOLDEN = json.loads((Path(__file__).parent / "data" / "r_golden.json").read_text())

SYNTH = {
    "outcome": [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5],
    "strata": ["a", "b", "a", "c", "b", "c", "a", "b", "c", "a", "b"],
    "weights": [1, 2, 1, 0.5, 3, 1, 2, 1, 1.5, 1, 2],
    "group": ["u", "v", "u", "v", "u", "v", "u", "v", "u", "v", "u"],
}


def _python_result(case, d):
    if case == "main":
        return strat(d["income"], d["big_class"], weights=d["weight"], group=d["education"])
    if case == "unweighted":
        return strat(d["income"], d["big_class"])
    if case == "micro":
        return strat(d["income"], d["micro_class"], weights=d["weight"])
    if case == "micro_ordered":
        return strat(d["income"], d["micro_class"], weights=d["weight"], ordered=True)
    if case == "synthetic":
        return strat(
            SYNTH["outcome"], SYNTH["strata"], weights=SYNTH["weights"], group=SYNTH["group"]
        )
    if case == "synthetic_ordered":
        return strat(SYNTH["outcome"], SYNTH["strata"], weights=SYNTH["weights"], ordered=True)
    raise AssertionError(case)


def _by_label(labels, values):
    return dict(zip([str(la) for la in labels], values, strict=True))


@pytest.mark.parametrize(
    "case", ["main", "unweighted", "micro", "micro_ordered", "synthetic", "synthetic_ordered"]
)
def test_strat_matches_r(case, cps):
    golden = GOLDEN[case]
    got = _python_result(case, cps)

    assert got.strat == pytest.approx(golden["strat"], rel=RTOL)
    assert got.std_error == pytest.approx(golden["std_error"], rel=RTOL)

    r_info = _by_label(golden["strata_info"]["strata"], golden["strata_info"]["share"])
    py_info = _by_label(got.strata_info["strata"], got.strata_info["share"])
    assert py_info == pytest.approx(r_info, rel=RTOL)
    r_prank = _by_label(golden["strata_info"]["strata"], golden["strata_info"]["s_prank"])
    py_prank = _by_label(got.strata_info["strata"], got.strata_info["s_prank"])
    assert py_prank == pytest.approx(r_prank, rel=RTOL)

    if "decomposition" in golden:
        # golden rows are [within, between]
        assert got.decomposition["within"]["weight"] == pytest.approx(
            golden["decomposition"]["weight"][0], rel=RTOL
        )
        assert got.decomposition["between"]["weight"] == pytest.approx(
            golden["decomposition"]["weight"][1], rel=RTOL
        )
        assert got.decomposition["within"]["strat"] == pytest.approx(
            golden["decomposition"]["strat"][0], rel=RTOL
        )
        assert got.decomposition["between"]["strat"] == pytest.approx(
            golden["decomposition"]["strat"][1], rel=RTOL
        )
        r_within = _by_label(golden["within_group"]["group"], golden["within_group"]["strat"])
        py_within = _by_label(got.within_group["group"], got.within_group["strat"])
        assert py_within == pytest.approx(r_within, rel=RTOL)
    else:
        assert got.decomposition is None


def test_srank_matches_r(cps):
    got = srank(cps["income"], cps["big_class"], weights=cps["weight"])
    golden = GOLDEN["srank_main"]
    r_share = _by_label(golden["strata"], golden["share"])
    py_share = _by_label(got.summary["strata"], got.summary["share"])
    assert py_share == pytest.approx(r_share, rel=RTOL)
    r_prank = _by_label(golden["strata"], golden["s_prank"])
    py_prank = _by_label(got.summary["strata"], got.summary["s_prank"])
    assert py_prank == pytest.approx(r_prank, rel=RTOL)


def test_micro_class_ordering_note(cps):
    """micro_class is numeric, so R's factor() and np.unique() sort it the
    same way — this is what makes the ordered=True cross-check meaningful."""
    assert cps["micro_class"].dtype == int
